import Link from 'next/link';
import { Sparkles, ArrowLeft } from 'lucide-react';
import styles from './page.module.css';
import PageVoiceControl from '@/components/PageVoiceControl';

export default function TermsPage() {
  return (
    <div className={styles.legalPage}>
      {/* Background Effects */}
      <div className={styles.bgMesh} aria-hidden="true" />
      <div className={styles.bgOrb1} aria-hidden="true" />
      
      <PageVoiceControl contentId="terms-main-content" pageTitle="Terms of Service" />

      <nav className={styles.nav}>
        <div className={styles.navInner}>
          <Link href="/" className={styles.logo}>
            <div className={styles.logoIcon}>
              <Sparkles size={20} />
            </div>
            <span className={styles.logoText}>EliteBooks</span>
          </Link>
          <Link href="/" className="btn btn-ghost" style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>
            <ArrowLeft size={16} /> Back to Home
          </Link>
        </div>
      </nav>

      <main className={styles.legalContent} id="terms-main-content">
        <div className={styles.legalHeader}>
          <h1>Terms of Service</h1>
          <p>Last updated: May 3, 2026</p>
        </div>

        <div className={`glass-card ${styles.legalBody}`}>
          <section>
            <h2>1. Acceptance of Terms</h2>
            <p>By accessing or using the EliteBooks platform ("Service"), you agree to be bound by these Terms of Service. If you do not agree to these terms, you may not use the Service.</p>
          </section>

          <section>
            <h2>2. Autonomous AI Agents</h2>
            <p>EliteBooks utilizes autonomous AI agents to perform accounting tasks, including but not limited to categorization, invoice generation, and payroll calculation. While our agents operate with an accuracy rate of 99.9%, you acknowledge that:</p>
            <ul>
              <li>You are ultimately responsible for the accuracy and completeness of your financial records.</li>
              <li>You must review tax documents and compliance reports generated by the Service before filing.</li>
              <li>The Service does not substitute for the advice of a certified professional accountant or legal counsel.</li>
            </ul>
          </section>

          <section>
            <h2>3. Subscription and Billing</h2>
            <p>Access to the Service requires a valid subscription. By providing payment information, you authorize us to charge your payment method on a recurring basis as per your selected plan. We reserve the right to suspend your account for non-payment.</p>
          </section>

          <section>
            <h2>4. Data Privacy & Security</h2>
            <p>Your privacy is important to us. Our data handling practices are governed by our Privacy Policy. By using EliteBooks, you consent to the processing of your financial data by our AI systems solely for the purpose of providing the Service.</p>
          </section>

          <section>
            <h2>5. Limitation of Liability</h2>
            <p>In no event shall EliteBooks, its creators, or its affiliates be liable for any indirect, incidental, special, or consequential damages arising out of or in connection with your use of the Service, including errors in accounting calculations or tax filings.</p>
          </section>
        </div>
      </main>

      <footer className={styles.footer}>
        <div className={styles.footerInner}>
          <p>&copy; {new Date().getFullYear()} EliteBooks. All rights reserved.</p>
        </div>
      </footer>
    </div>
  );
}
